'use client'
import Providers from "@/store/provider";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import ModalManager from "@/components/ModalManager/ModalManager";
import './globals.scss';

// export const metadata = {
//   title: '.adamb',
//   description: 'Generated by create next app',
// };

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar/>
          {children}
          <Footer/>
          <ModalManager/>
        </Providers>
      </body>
    </html>
  );
}
