'use client'
import NavBar from "../components/NavBar/NavBar";
import Footer from "../components/Footer/Footer";
import ModalManager from "../components/ModalManager/ModalManager";
import {Provider} from 'react-redux';
import {store} from '../store/store';
import {Toaster} from "react-hot-toast";
import './globals.scss';

// export const metadata = {
//   title: '.adamb',
//   description: 'Generated by create next app',
// };

export default function RootLayout({children} : {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <NavBar/>
          {children}
          <Footer/>
          <ModalManager/>
          <Toaster/>
        </Provider>
      </body>
    </html>
  );
}
